### ISSUE TITLE
CHIRP compatability

### ISSUE THREAD

**Issue by Big-Mal99** [armel/uv-k5-firmware-custom-feat-F4HWN#13]
Experimening with this firmware - first impressions very good - but it appears to not work with CHIRP unless I have issed a link somewhere.  Please advise

**Comment by armel** [comment]
You need to use an external driver.
Take a look here https://github.com/armel/uv-k5-chirp-driver
Of course, please, read the README...

Armel F4HWN

**Comment by Big-Mal99** [comment]
Armel

Thanks for the prompt reply.  I must have missed that somehow.

Malcolm 2E0UMT

**Comment by armel** [comment]
You're welcome.

Armel F4HWN
