### ISSUE TITLE
Plantage en scan

### ISSUE THREAD

**Issue by EricBx33** [armel/uv-k5-firmware-custom-feat-F4HWN#15]
Bonjour.
Je vais essayer d'être le plus clair possible.
J'ai une centaine de canaux mémorisés : 16 PMR +2 +88 bande marine.
Quand j'essaie de scanner les canaux PMR voila ce qu'il se passe : 
Je mets la mémoire 001 sur la ligne A, la mémoire 16 sur la ligne B.
Quand j'essaie de lancer le scan sur ces canaux la ligne B saute à la mémoire 030 et toute la radio est bloquée : plus aucune touche ne fonctionne, je suis obligé de l'éteindre. 
Quand je la remet en marche la ligne A a bien la mémoire 001 d'affichée et la ligne B la mémoire 016.
Les canaux ont été programmés via CHIRP, la radio est une Quansheng UV-5R Plus.

**Comment by armel** [comment]
Bonjour,

Vous faites un Scan ou un ScanRange ?
Vous avez le même problème avec le firmware Egzumer v0.22 d'origine ?
Il est possible d'avoir l'export de votre configuration Chirp pour que je tente de reproduire la manip ?

F4HWN

**Comment by EricBx33** [comment]
Je n'ai pas essayé avec le egzumzer d'origine.
Je fais un scan touche */Scan ou F2
[Quansheng_UV-K5 (egzumer + f4hwn)_20240227.csv](https://github.com/armel/uv-k5-firmware-custom-feat-F4HWN/files/14422937/Quansheng_UV-K5.egzumer.%2B.f4hwn._20240227.csv)
.
Je viens de me rendre que la touche Menu ou Exit semble sortir la radio de la boucle : l'affichage reviens sur ce qu'il y avait et les touches re-fonctionnent.

**Comment by armel** [comment]
Ok. Si vous faites un Scan par */Scan (ou via un raccourcis sur F2), ca lance un Scan simple (à ne pas confondre avec un Scanrange) sur le VFO en cours de sélection (donc inutile de mettre la mémoire 001 sur la ligne A, la mémoire 16 sur la ligne B...).

En l'état, pour moi, tout est fonctionnel. 

Quand je lance un tel Scan, il parcours les 75 canaux mémoire que vous avez enregistrés, ce qui est normal.
 
Je vous suggère éventuellement d'utiliser en complément les notions de listes. Par exemple, affecter les canaux PMR à la liste 1 et les canaux maritime à la liste 2. 

Bref, je n'arrive pas à reproduire votre problème.

F4HWN.

**Comment by EricBx33** [comment]
Voulez-vous que je fasse une vidéo ?

**Comment by armel** [comment]
Si vous voulez.

F4HWN.

**Comment by EricBx33** [comment]
Impossible de faire une video de moins de 10Mo pour la poster directement...

https://drive.google.com/file/d/1mRDIZRBMnPYVU3WxlPf10wpEJyHkVtB5/view?usp=drive_link

**Comment by armel** [comment]
Postez là sur Youtube (par exemple, en vidéo non répertoriée).

F4HWN.

**Comment by EricBx33** [comment]
En fait vous avez raison, c'est un problème dans mes scanlist et un comportement auquel je ne m'attendais pas...
Je suis désolé de vous avoir fait perdre votre temps.
Bonne journée.

**Comment by armel** [comment]
Pas de souci, ce n'est rien.
Je ferme l'issue.

F4HWN.

**Comment by armel** [comment]
Résolu, problème de prise en main des scanlists.
