### ISSUE TITLE
question about firmware

### ISSUE THREAD

**Issue by tacva** [armel/uv-k5-firmware-custom-feat-F4HWN#16]
Hello, is your firmware version open source? Because I didn't understand, probably due to my incompetence, how it's possible to view individual code files. Do you plan to publish the source code or, as I seem to understand, only the compiled versions? Thank you very much for your excellent work.

**Comment by armel** [comment]
Hello,

Yes of course, it's full open source.
Take a look a this repo https://github.com/armel/uv-k5-firmware-custom and check branch.

Armel.

**Comment by tacva** [comment]
Thank you very much and sorry, I had searched for a long time but I really don't know why, I couldn't find the source files. Thanks again!
