### ISSUE TITLE
Info Display Scan (ver 2.0)

### ISSUE THREAD

**Issue by vfsouza7** [armel/uv-k5-firmware-custom-feat-F4HWN#17]
Firstly, thank you very much for your efforts.  We have a perfect firmware for our Quansheng!  I updated my radio to version 2.0, but when I press and hold the Scan button (* Scan) the display only shows List 1 even though it is in List 2.

**Comment by armel** [comment]
Hi,

Thank you.
Sorry, I can't reproduce this ?!

Armel.
