### ISSUE TITLE
scan partiel main only

### ISSUE THREAD

**Issue by f4axk** [armel/uv-k5-firmware-custom-feat-F4HWN#23]
slt Armel

Vue sur le groupe facebook UV-K5 FRANCE
Mode Main Only
Quand on utilise le scan partiel en VFO et que ensuite on veut passer en mode mémoires  ,
sans être sortie du mode scan partiel.
j'ai pu le constater

![moscan-1](https://github.com/armel/uv-k5-firmware-custom-feat-F4HWN/assets/68162981/e474d4d7-eec8-4718-a26b-019c38db232f)
![moscan-2](https://github.com/armel/uv-k5-firmware-custom-feat-F4HWN/assets/68162981/b3531625-bf4e-43e8-93ba-cbad6727f772)

**Comment by armel** [comment]
Bonjour Laurent,

Merci pour ce retour. Oui, j'arrive à reproduire ce bug d'affichage. 
Il m'avait été remonté par Pascal F4ICR, il y a quelques jours.
Je tenterais de le fixer mais... pas sûr que cela rentre.

73'

Armel F4HWN

**Comment by f1ixx** [comment]
Bonjour

Comme deja dit, je ne suis tres tres loin d'etre un specialiste en progammation.
J'ai modifier dans le fichier ui/main.c - Ligne 646<br>
ancien code : <code>if (gScanRangeStart) { </code><br>
nouveau code : <code>if ( (gScanRangeStart) && (IS_MR_CHANNEL(gEeprom.ScreenChannel[vfo_num]) == false) ) { </code><br>
Il fort possible que j'ajoute plus de mal que de bien. D'apres les quelques essais, ca semble
fonctionner sur ma compilatio.

Merci

Boris

**Comment by armel** [comment]
Le bug sera fixé dans la v2.3

Armel F4HWN.
