### ISSUE TITLE
Which CHIRP version?

### ISSUE THREAD

**Issue by KDMcMullan** [armel/uv-k5-firmware-custom-feat-F4HWN#24]
Hi. I cannot get this to work with the new version of CHIRP. According to egzumer, the egzumer driver is now included in CHIRP but I'm getting "Firmware 'F4HWN v2.2' is not supported."
The F4HWN mod seems to work with egzumer's own CHIRP build.
Any thoughts what might be going on there?
Thanks.

**Comment by f1ixx** [comment]
Hi

You can find a special nice version [here](https://github.com/armel/uv-k5-chirp-driver)
and have some help to use it.

Best regard
Boris

**Comment by KDMcMullan** [comment]
Indeed, this is the one which works for me. Thank you.
HOWEVER, the question is: given that CHIRP and egzumer both say that the egzumer driver is included in CHIRP now, I wonder why CHIRP doesn't work with the F4HWN mod?

**Comment by f1ixx** [comment]
Some function work with Egzumer, but haven't full function.
And Chirp use signature version to detect if driver is correct (eg 2.0 and 2.5).
F4HWN make many mods

**Comment by KDMcMullan** [comment]
Je crois que CHIRP effectue des certaine validations et que le driver effectue également les autres.
J'ai remarqué que je ne peux pas non plus utiliser le nouveau CHIRP avec un egzumer "normale", puisque je ne suis pas autorisé (par CHIRP, j'imagine) a entrer des fréquences de bande de 11m.

**Comment by armel** [comment]
Hi,

My firmware is experimental. As long as my firmware continues to evolve, you'll need to use the dedicated driver. If, and only if, my firmware stabilizes and becomes widely used (like Egzumer's), Chirp may choose to add it natively. But we're a long way from that. 

Now, note that using a dedicated driver is not complicated. It's just a little effort. 

73'

Armel F4HWN.

**Comment by KDMcMullan** [comment]
I'm perfectly happy and comfortable to continue to use egzumer's driver. It's no chore at all. I'll also be continuing to use your firmware, as I really like the way it is shaping up.

I don't fully grasp the connections between the versions and their drivers. I present the following as facts:
- It's not clear that your users still need to use egzumer's driver.
- It's not clear why, even though egzumer's sriver IS now included in CHIRP, it still doesn't work.

I wonder if uptake of your build might be larger if folk weren't upset and put off my CHIRP telling them it doesn't work?

Hope this is helpful.
