### ISSUE TITLE
Et si ...

### ISSUE THREAD

**Issue by Daffouille** [armel/uv-k5-firmware-custom-feat-F4HWN#27]
Bonjour Armel,

La mémoire étant saturée, une des solutions est de supprimer la FM ...

Je me disais que l'appareil va perdre une de ses fonctions, qui n'est pas primordiale ...

Mais entre tout supprimer, ou ne conserver qu'une fonction FM très minimaliste (pas de scan, pas de mémorisation ... juste taper la fréquence ... ou autre solution ... quelque chose de basique), n'y aurait-il pas une piste à étudier ?

Merci pour ton travail en tout cas.

Stéphane

**Comment by armel** [comment]
Bonsoir Stéphane,

J'ai quelques doutes sur le gain. 
Ce qui bouffe de la mémoire, c'est surtout la prise en charge du BK1080 dédié à la Broadcast FM... 
Mais je regarderais à l'occasion.

73'

Armel F4HWN.
