### ISSUE TITLE
Passage a main only en mode scan

### ISSUE THREAD

**Issue by fifisoft57** [armel/uv-k5-firmware-custom-feat-F4HWN#28]
bonjour

je viens de faire un test, j'ai lancer un scan sur la VFO B , j'ai programmer une touche F2 long pour changer de main only a normal

quand je changer et que le scan est en route , le scan continue en main only ( normal ) mais que je repasse sur l'autre affichage , le scan passe sur la VFO A et si je rappuies encore la ca passe sur la VFO B ( le scan continue )

a voir si  c'est normal ? 

merci pour se firmware qui est super et encore un super boulot

Philippe

**Comment by armel** [comment]
Bonjour Philippe,

Laurent a parfaitement expliqué l'origine du phénomène. Je n'ai rien à ajouté :)

Armel.

**Comment by fifisoft57** [comment]
merci bcp pour vos retour
