### ISSUE TITLE
To big file f4hwn.packed.v2.3

### ISSUE THREAD

**Issue by mpmdembi** [armel/uv-k5-firmware-custom-feat-F4HWN#31]
When I try to flash this FW - "The size of this file is to much!" :-(  Flashing 2.2 with no problem.

**Comment by armel** [comment]
Probably because you're using the wrong tool to flash.
Why don't you use the [online flasher](https://egzumer.github.io/uvtools/?firmwareURL=https://github.com/armel/uv-k5-firmware-custom-feat-F4HWN/raw/main/f4hwn.packed.bin) ?

Armel F4HWN
