### ISSUE TITLE
No TX translation with external microphone in monitoring mode.

### ISSUE THREAD

**Issue by FAH5502** [armel/uv-k5-firmware-custom-feat-F4HWN#37]
I have a probleme with the external microphone PTT in monitoring mode or squelch at 0.
the PTT button not working as intended.
but the PTT on the radio work well in monitoring mode.
can you fix this problem.
Best regards.
FAH5502.
Marc

**Comment by armel** [comment]
Marc, sorry, it's not a firmware issue. 
It's a microphone (and hardware) issue.

Take a look here :

![405547157_1459776488218037_3584156213437175277_n](https://github.com/armel/uv-k5-firmware-custom-feat-F4HWN/assets/127889/869ccedc-2acb-41b7-be8c-2201af51b7fa)

Armel F4HWN.

**Comment by oe3jtb** [comment]
or you modify the radio itself, its easy to do https://github.com/ludwich66/Quansheng_UV-K5_Wiki/wiki/Hardware_Mods#5-fix-power-failure-with-external-handset-warming-speaker-with-dc-on-output-or-unwanted-busy-channel-lockout-effect-on-external-ptt
