### ISSUE TITLE
Prochaine évolution (à mon sens)

### ISSUE THREAD

**Issue by Daffouille** [armel/uv-k5-firmware-custom-feat-F4HWN#42]
Bonjour Armel

Le prochain gap qui mériterait la consommation d'octets supplémentaires serait - à mon idée - la compatibilité DMR ...

C'est juste une proposition, rien de plus ...

Merci encore pour ton travail réalisé, car ton FW est vraiment utile, et axé utilisateurs.

Stéphane, un SWL qui n'a pas encore franchi la barrière des RA ...

**Comment by armel** [comment]
Bonjour Stéphane,

J'ai regardé si nous étions le premier avril, mais non :) 

Bon, techniquement, c'est tout simplement impossible. Le DMR suppose l'utilisation de CODEC numérique. L'électronique du K5 n'a pas du tout ce qu'il faut pour. Par comparaison, un GD77 a 1 Mo de mémoire flash (contre 64 Ko pour le K5). 
Donc non, aucun espoir la dessus avec ce poste. 

Et ca tombe bien, je déteste le DMR. C'est un mode de communication pour les sheriffs, les pompiers, les... professionnels. L'analogique lui est bien supérieur sur des signaux faibles. 

Mais rassure toi, Quansheng s'y intéresse et va très probablement sortir un nouveau poste compatible DMR prochainement, d'après les infos que j'ai ;) 

Armel F4HWN.

**Comment by armel** [comment]
Hors sujet :)
