### ISSUE TITLE
Not supported by CHIRP ?

### ISSUE THREAD

**Issue by z34pec** [armel/uv-k5-firmware-custom-feat-F4HWN#47]
Hello.
When I try to acccess UVK5 with latest firmware 2.5 I receive message that firmwaer is not supported.
Also happened version before of chirp but this time it was IJV 2.7.

![image](https://github.com/armel/uv-k5-firmware-custom-feat-F4HWN/assets/133197383/3314c8dc-fc70-4b7f-980c-9eeaa4e99a0b)

**Comment by z34pec** [comment]
I think find a solution.
I think this module should be added to your existing files.

https://chirpmyradio.com/issues/11270

**Comment by f1ixx** [comment]
Hello
you can also read [driver here](https://github.com/armel/uv-k5-chirp-driver)

73's
Boris

**Comment by armel** [comment]
Hi,

My firmware as many others need a dedicated driver. Take a look at [this](https://github.com/armel/uv-k5-chirp-driver) :) 

Regards,

Armel F4HWN

**Comment by z34pec** [comment]
Thanks. I think this driver should be added in FW package.
