### ISSUE TITLE
MR->VFO and cycling through the bands

### ISSUE THREAD

**Issue by lapinos03** [armel/uv-k5-firmware-custom-feat-F4HWN#49]
1. go to VFO mode. Enter a frequency (let's call it F1)
2. go to MR mode. Copy you MR to VFO (F+1) (let's call it F2)
3. do cycle through out the bands until you return to the first band -> F1 is shown. It that normal ? (I would expect to see F2)

You can redo the steps. At step #2, change F2 (with UP or DOWN key). At step #3 then you will find F2 as expected.

**Comment by armel** [comment]
Will be fixed in v2.6
