### ISSUE TITLE
Changing mode with long-press M key not persistent

### ISSUE THREAD

**Issue by lapinos03** [armel/uv-k5-firmware-custom-feat-F4HWN#51]
Changing mode through the menu is persistent.

But when you change it with a long press on the M key, the change is not persistent (on power-on, it returns to the mode that was set through the menu).

Is that normal ?

**Comment by armel** [comment]
Yes. It's not a bug, it's a feature... :)
It's normal.

Armel F4HWN.

**Comment by 4ndy1** [comment]
Could you do anything with the squelch tail it’s like a branch snapping
