### ISSUE TITLE
Burst tone when MONITOR is active doesn't keep the squelch open

### ISSUE THREAD

**Issue by lapinos03** [armel/uv-k5-firmware-custom-feat-F4HWN#54]
1. activate the monitoring (left button #1), the loudspeaker plays some blank noise and MONI is displayed on the screen ;
2. tx the 1750 Hz tone and release the corresponding key ;
3. loudspeaker remains silent while MONI still displayed.

Tested in DW/DWR/MO modes, v2.3 and v2.5.

**Comment by armel** [comment]
Thank you very much 👍 
Will be fixed in v2.6

Armel F4HWN.

**Comment by armel** [comment]
Fixed in v2.6
