### ISSUE TITLE
Leftovers on LCD screen RX timer running in Scan mode

### ISSUE THREAD

**Issue by spamsool** [armel/uv-k5-firmware-custom-feat-F4HWN#57]
I like the new RX timer running when receiving transmission however there is a small bug on the screen when RX starts from Scan mode.
Depending on which Scanlist is active (I, II or all) there is a leftover of the Scanlist symbol on the runing time sticked to the timer.

![qua](https://github.com/armel/uv-k5-firmware-custom-feat-F4HWN/assets/6050352/437cede7-917d-4908-bab1-20d301a2f54e)

**Comment by armel** [comment]
Thank you. Ok, that's a bug. I plan to fix it in the next release :)

Armel F4HWN.

**Comment by armel** [comment]
Fixed in v2.7
