### ISSUE TITLE
Error en el ltime

### ISSUE THREAD

**Issue by CARLITOS-EA30346FD** [armel/uv-k5-firmware-custom-feat-F4HWN#58]
En esta última versión la v2.6 puedes configurar el tiempo de txen el menu 35, pues por mucho que le pongas 2 o 3 min solo te deja hablar 1 min pero la configuracion del  menú lo canvia, Gracias por tu trabajo cada vez que utilizo este firmware me gusta más 73's

**Comment by armel** [comment]
Creo que confundes el menú 35 BLTime, relativo a la retroiluminación de la pantalla, con el menú 28 TxTOut, relativo al TOT :)

**Comment by CARLITOS-EA30346FD** [comment]
Ok perdón me lie muchas gracias
