### ISSUE TITLE
Switching to Broadcast FM while RX active will lock the keyboard

### ISSUE THREAD

**Issue by lapinos03** [armel/uv-k5-firmware-custom-feat-F4HWN#62]
Hello !

I wanted to listen to Broadcast FM (keys F+0) while the radio was receiving a (continously transmitting) channel and it didn't switch to it. Actually the keyboard was locked while the display showed FM in the top left corner.

If the channel stops receiving then after a few seconds of silence, the radio switches to Broadcast FM and then you can handle the keys as normal. Otherwise the only solution is to power off/on (or to remove antenna to drop down the signal).

This happens when receiving on the TX channel only, whatever VFO-A or B.

Tested in bands 440 and 1200 MHz. Version 2.5. Reproductible anytime.

**Comment by armel** [comment]
Hello,

I think this is normal and I'm not sure what to do about it. The K5 uses 2 ICs for the radio. The BK1080 for FM Broadcast and the BK4819 for all the rest. The BK4819 obviously has priority. If a signal is received on the BK4819, the BK1080 is no longer active. It becomes active again after a delay, in the absence of a signal on the BK4819, which is normal again. 

Armel F4HWN.
