### ISSUE TITLE
Chips Support?

### ISSUE THREAD

**Issue by N8ZC** [armel/uv-k5-firmware-custom-feat-F4HWN#73]
Will Chirps support be coming any time soon?

I really like your fireware version, but...  Without Chirps support, why use this?  Good thing I don't have too make any changes to memory channels, for now.  Programming direct in the radio is simly a pain.

**Comment by misterbig** [comment]
uv-k5-chirp-driver
https://github.com/armel/uv-k5-chirp-driver

**Comment by N8ZC** [comment]
THANK YOU!
I should dug a bit deeper and after the first cup of coffee... Or, maybe the second.

Thanks again!

**Comment by BastelPichi** [comment]
@N8ZC you mind closing this issue? Its resolved after all, isnt it.

**Comment by N8ZC** [comment]
sorry.  i'm a newby here.
