### ISSUE TITLE
F+1 does not make VFO mode persistent after power off/on

### ISSUE THREAD

**Issue by lapinos03** [armel/uv-k5-firmware-custom-feat-F4HWN#75]
Hi there!

1. choose a MR channel
2. F+1 to copy it to VFO mode (and optionally change the frequency with UP/DOWN keys)
3. power off/on radio
4. MR channel is displayed instead of VFO

To me, (F+1) is same as (copy MR to VFO) + (F+3 = switch to VFO mode). If F+3 remains persistent after power off/on, so must be F+1 too. 

Versions : 2.7, 2.6

**Comment by armel** [comment]
Ok. Will be fix in v2.7 !
Thank you,

Armel F4HWN.

**Comment by armel** [comment]
Fixed in v2.7
